# Introduction to NumPy

In [5]:
import numpy as np  #importing numpy packages
x=np.array([4,3,2,1]) 
y=2*x    #creating second row as y 
print("{}\n{}".format(x,y)) #printing x and y as first and second row

[4 3 2 1]
[8 6 4 2]


In [ ]:
From Normal list

In [14]:
x=[4,3,2,1]
y= 2*x
print("{}\n{}".format(x,y))

[4, 3, 2, 1]
[4, 3, 2, 1, 4, 3, 2, 1]


In [15]:
x = np.arange(0,100, 1) #range function
print(x[[4,5,6,7,8,9,10]])

[ 4  5  6  7  8  9 10]


In [19]:
x = [1,2,3,4,5,6,7,8,9,10]
print(x[[0,1,2]])

TypeError: list indices must be integers or slices, not list

So we just remove list 

In [29]:
x = [1,2,3,4,5,6,7,8,9,10]
print([x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],x[8],x[9]])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]]) #array function
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
print(x.ndim) # number of dimensions
print(x.shape) # Shape of array
print(x.size) # Total number of elements

2
(3, 3)
9


In [33]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [34]:
np.matrix(x)*np.matrix(x)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [35]:
np.dot(x,x)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [36]:
x>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [37]:
x<5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [49]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.copy(x) 
y[y>5]=0
y

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

In [53]:
y=np.delete(x,5) #deleting the elements
y

array([1, 2, 3, 4, 5, 7, 8, 9])

In [54]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
index=np.where(x[:,0]>5)
y=np.delete(x,index,axis=1) #removing columns
print(y)

[[1 2]
 [4 5]
 [7 8]]


In [56]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
index=np.where(x[:,0]>5)
y=np.delete(x,index,axis=0) #removing rows
print(y)

[[1 2 3]
 [4 5 6]]


In [57]:
np.arange(0,1,0.1) #using step size 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [60]:
x = np.arange(-np.pi, np.pi, 0.1)
x

array([-3.14159265, -3.04159265, -2.94159265, -2.84159265, -2.74159265,
       -2.64159265, -2.54159265, -2.44159265, -2.34159265, -2.24159265,
       -2.14159265, -2.04159265, -1.94159265, -1.84159265, -1.74159265,
       -1.64159265, -1.54159265, -1.44159265, -1.34159265, -1.24159265,
       -1.14159265, -1.04159265, -0.94159265, -0.84159265, -0.74159265,
       -0.64159265, -0.54159265, -0.44159265, -0.34159265, -0.24159265,
       -0.14159265, -0.04159265,  0.05840735,  0.15840735,  0.25840735,
        0.35840735,  0.45840735,  0.55840735,  0.65840735,  0.75840735,
        0.85840735,  0.95840735,  1.05840735,  1.15840735,  1.25840735,
        1.35840735,  1.45840735,  1.55840735,  1.65840735,  1.75840735,
        1.85840735,  1.95840735,  2.05840735,  2.15840735,  2.25840735,
        2.35840735,  2.45840735,  2.55840735,  2.65840735,  2.75840735,
        2.85840735,  2.95840735,  3.05840735])

In [63]:
y = np.sin(x)
y

array([-1.22464680e-16, -9.98334166e-02, -1.98669331e-01, -2.95520207e-01,
       -3.89418342e-01, -4.79425539e-01, -5.64642473e-01, -6.44217687e-01,
       -7.17356091e-01, -7.83326910e-01, -8.41470985e-01, -8.91207360e-01,
       -9.32039086e-01, -9.63558185e-01, -9.85449730e-01, -9.97494987e-01,
       -9.99573603e-01, -9.91664810e-01, -9.73847631e-01, -9.46300088e-01,
       -9.09297427e-01, -8.63209367e-01, -8.08496404e-01, -7.45705212e-01,
       -6.75463181e-01, -5.98472144e-01, -5.15501372e-01, -4.27379880e-01,
       -3.34988150e-01, -2.39249329e-01, -1.41120008e-01, -4.15806624e-02,
        5.83741434e-02,  1.57745694e-01,  2.55541102e-01,  3.50783228e-01,
        4.42520443e-01,  5.29836141e-01,  6.11857891e-01,  6.87766159e-01,
        7.56802495e-01,  8.18277111e-01,  8.71575772e-01,  9.16165937e-01,
        9.51602074e-01,  9.77530118e-01,  9.93691004e-01,  9.99923258e-01,
        9.96164609e-01,  9.82452613e-01,  9.58924275e-01,  9.25814682e-01,
        8.83454656e-01,  

In [64]:
x_abs = np.abs(x)
x_abs 

array([3.14159265, 3.04159265, 2.94159265, 2.84159265, 2.74159265,
       2.64159265, 2.54159265, 2.44159265, 2.34159265, 2.24159265,
       2.14159265, 2.04159265, 1.94159265, 1.84159265, 1.74159265,
       1.64159265, 1.54159265, 1.44159265, 1.34159265, 1.24159265,
       1.14159265, 1.04159265, 0.94159265, 0.84159265, 0.74159265,
       0.64159265, 0.54159265, 0.44159265, 0.34159265, 0.24159265,
       0.14159265, 0.04159265, 0.05840735, 0.15840735, 0.25840735,
       0.35840735, 0.45840735, 0.55840735, 0.65840735, 0.75840735,
       0.85840735, 0.95840735, 1.05840735, 1.15840735, 1.25840735,
       1.35840735, 1.45840735, 1.55840735, 1.65840735, 1.75840735,
       1.85840735, 1.95840735, 2.05840735, 2.15840735, 2.25840735,
       2.35840735, 2.45840735, 2.55840735, 2.65840735, 2.75840735,
       2.85840735, 2.95840735, 3.05840735])

In [65]:
y2 = np.exp(x)
y2

array([ 0.04321392,  0.04775877,  0.0527816 ,  0.05833269,  0.06446759,
        0.07124771,  0.07874089,  0.08702214,  0.09617434,  0.10628909,
        0.11746761,  0.12982179,  0.14347526,  0.15856469,  0.17524108,
        0.19367135,  0.21403994,  0.23655072,  0.26142897,  0.2889237 ,
        0.31931007,  0.3528922 ,  0.3900062 ,  0.43102351,  0.47635464,
        0.5264533 ,  0.58182087,  0.64301151,  0.71063762,  0.78537603,
        0.86797475,  0.95926045,  1.06014675,  1.17164336,  1.29486617,
        1.43104843,  1.58155311,  1.7478865 ,  1.93171333,  2.1348734 ,
        2.35939999,  2.60754026,  2.88177766,  3.18485686,  3.51981118,
        3.88999295,  4.29910708,  4.75124812,  5.25094125,  5.80318756,
        6.41351413,  7.0880293 ,  7.83348384,  8.65733853,  9.56783877,
       10.57409716, 11.68618467, 12.91523144, 14.27353818, 15.7746993 ,
       17.43373891, 19.26726123, 21.29361679])

In [66]:
np.where?

# Assignment

In [ ]:
#Part 1: Finding distance considering only high probability stars

In [68]:
beehive_data = np.loadtxt('Beehive_data.csv', delimiter=',')

In [69]:
indices = np.where(beehive_data[:, 2]>90)
high_prob = beehive_data[indices] 

In [70]:
logd = (high_prob[:,0] + 2.5*high_prob[:,1] + 0.17)/5 
                                                        
d = 10**logd 

In [71]:
sum_of_dist = 0
for i in d: #Here we take the sum of all elements in the array
    sum_of_dist = sum_of_dist + i
dist_of_cluster= sum_of_dist/d.size #Answer is the average
print(dist_of_cluster)

159.9814397624894


In [ ]:
#Part 2: Finding distance by taking average weighted by probabilities

In [73]:
logd_full = (beehive_data[:,0] + 2.5*beehive_data[:,1] + 0.17)/5 
d_full = 10**logd_full
weighted_dist = d_full * beehive_data[:,2] 
weighted_sum = 0
sum_of_weights = 0
for i in range(0, weighted_dist.size):
    weighted_sum = weighted_sum + weighted_dist[i] 
    sum_of_weights = sum_of_weights + beehive_data[i,2] 
weighted_dist_of_cluster = weighted_sum/sum_of_weights 
print(weighted_dist_of_cluster)

159.5464083490186
